(() => {
'use strict';
const $=id=>document.getElementById(id), cfg=window.OSTL_SUPABASE;
if(!cfg?.url || !cfg?.anonKey || cfg.url.includes('PASTE_')) throw Error('Open supabase-config.js and add your Supabase URL and publishable/anon key.');
const sb=window.supabase.createClient(cfg.url,cfg.anonKey,{auth:{persistSession:true,autoRefreshToken:true}});
const params=new URLSearchParams(location.search), DOMAIN='ozarktravelstein.app';
let S={user:null,role:'spectator',group:1,tid:null,t:null,players:[],scores:[],channel:null,hole:1};
const show=id=>['login','home','create','event'].forEach(x=>$(x).classList.toggle('hidden',x!==id));
const toast=m=>{$('toast').textContent=m;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2800)};
const status=(m,e=false)=>{$('status').textContent=m;$('status').classList.toggle('error',e)};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const usernameEmail=v=>{const u=String(v||'').trim().toLowerCase();if(!/^[a-z0-9._-]{3,30}$/.test(u))throw Error('Username must be 3–30 letters, numbers, dots, dashes, or underscores.');return `${u}@${DOMAIN}`};
const randomToken=()=>Array.from(crypto.getRandomValues(new Uint8Array(24)),b=>b.toString(16).padStart(2,'0')).join('');
const check=({error})=>{if(error)throw error};
function groups(el){el.innerHTML=Array.from({length:6},(_,i)=>`<option value="${i+1}">Group ${i+1}</option>`).join('')}; groups($('playerGroup'));groups($('groupSelect'));
async function anonymous(){let {data}=await sb.auth.getSession();if(data.session)return data.session.user;const r=await sb.auth.signInAnonymously();check(r);return r.data.user}
async function boot(){try{if(params.get('t')&&params.get('g')&&params.get('token')){await anonymous();const r=await sb.rpc('claim_group_link',{p_tournament:params.get('t'),p_group:Number(params.get('g')),p_token:params.get('token')});check(r);S.role='group';S.group=Number(params.get('g'));await openEvent(params.get('t'));return}if(params.get('spectator')){await anonymous();const r=await sb.from('tournaments').select('id').eq('is_active',true).order('created_at',{ascending:false}).limit(1).maybeSingle();check(r);if(!r.data)throw Error('No active tournament is selected.');S.role='spectator';await openEvent(r.data.id);return}const {data}=await sb.auth.getSession();if(data.session?.user && !data.session.user.is_anonymous){S.user=data.session.user;S.role='admin';await loadHome()}else{show('login');status('Administrator sign-in required.')}}catch(e){status(e.message,true);show('login')}}
$('loginBtn').onclick=async()=>{try{const r=await sb.auth.signInWithPassword({email:usernameEmail($('username').value),password:$('password').value});check(r);S.user=r.data.user;S.role='admin';await loadHome()}catch(e){status(e.message,true)}};
$('registerBtn').onclick=async()=>{try{const r=await sb.auth.signUp({email:usernameEmail($('username').value),password:$('password').value});check(r);if(!r.data.session)throw Error('Account created, but email confirmation is enabled. Turn Confirm email off in Supabase Auth settings, then sign in.');S.user=r.data.user;S.role='admin';await loadHome()}catch(e){status(e.message,true)}};
$('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.href=location.pathname}; $('spectatorBtn').onclick=()=>location.href='?spectator=1';
$('newBtn').onclick=()=>show('create');document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show('home'));$('backBtn').onclick=()=>{unsubscribe();loadHome()};
async function loadHome(){show('home');status('Connected as administrator.');const r=await sb.from('tournaments').select('*').order('date',{ascending:false});check(r);$('tournaments').innerHTML=!r.data.length?'<p>No tournaments yet.</p>':r.data.map(t=>`<button class="secondary full eventBtn" data-id="${t.id}">${esc(t.name)} — ${esc(t.course||'')}</button>`).join('');document.querySelectorAll('.eventBtn').forEach(b=>b.onclick=()=>openEvent(b.dataset.id))}
$('createBtn').onclick=async()=>{try{const holes=Number($('newHoles').value),pars=Array.from({length:holes},(_,i)=>[4,4,3,5,4,4,3,5,4][i%9]),stroke=Array.from({length:holes},(_,i)=>i+1);const u=(await sb.auth.getUser()).data.user;if(!u)throw Error('Your admin session expired. Sign in again.');const r=await sb.from('tournaments').insert({admin_user_id:u.id,name:$('newName').value.trim(),course:$('newCourse').value.trim(),date:$('newDate').value,holes,pars,stroke_indexes:stroke}).select().single();check(r);await openEvent(r.data.id)}catch(e){status(e.message,true)}};
function unsubscribe(){if(S.channel){sb.removeChannel(S.channel);S.channel=null}}
async function openEvent(id){S.tid=id;show('event');unsubscribe();await reloadEvent();S.channel=sb.channel(`event:${id}`).on('postgres_changes',{event:'*',schema:'public',table:'scores',filter:`tournament_id=eq.${id}`},reloadScores).on('postgres_changes',{event:'*',schema:'public',table:'players',filter:`tournament_id=eq.${id}`},reloadPlayers).on('postgres_changes',{event:'UPDATE',schema:'public',table:'tournaments',filter:`id=eq.${id}`},reloadTournament).subscribe();status(`Connected • ${S.role}`)}
async function reloadEvent(){await Promise.all([reloadTournament(),reloadPlayers(),reloadScores()])}
async function reloadTournament(){const r=await sb.from('tournaments').select('*').eq('id',S.tid).single();check(r);S.t=r.data;renderAll()}
async function reloadPlayers(){const r=await sb.from('players').select('*').eq('tournament_id',S.tid).order('name');check(r);S.players=r.data||[];renderAll()}
async function reloadScores(){const r=await sb.from('scores').select('*').eq('tournament_id',S.tid);check(r);S.scores=r.data||[];renderAll()}
const admin=()=>S.role==='admin';
function renderAll(){if(!S.t)return;$('eventName').textContent=S.t.name;$('eventMeta').textContent=`${S.t.course||''} • ${S.t.date||''} • ${S.t.holes} holes`;$('roleBadge').textContent=admin()?'ADMIN':S.role==='group'?`GROUP ${S.group}`:'SPECTATOR';renderLeader();renderScores();renderPlayers();renderSetup();renderSkins()}
document.querySelectorAll('[data-tab]').forEach((b,i)=>{if(i===0)b.classList.add('active');b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.pane').forEach(x=>x.classList.add('hidden'));const id=b.dataset.tab;if((id==='players'||id==='setup')&&!admin()){toast('Administrator only');document.querySelector('[data-tab="leader"]').click();return}$(id).classList.remove('hidden');renderAll()}});
function strokesOnHole(handicap,hole){const hc=Number(handicap||0), holes=S.t.holes, si=Number(S.t.stroke_indexes?.[hole-1]||hole);if(hc===0)return 0;const sign=hc<0?-1:1, abs=Math.abs(hc), base=Math.floor(abs/holes), rem=abs%holes;return sign*(base+(si<=rem?1:0))}
function net(p,h,gross){return gross-strokesOnHole(p.course_handicap,h)}
function renderLeader(){const rows=S.players.map(p=>{const ss=S.scores.filter(s=>s.player_id===p.id),par=ss.reduce((a,s)=>a+(S.t.pars?.[s.hole-1]||4),0),n=ss.reduce((a,s)=>a+net(p,s.hole,s.gross),0);return{p,thru:ss.length,val:n-par}}).sort((a,b)=>a.val-b.val);$('leader').innerHTML='<h2>Net Leaderboard</h2>'+(!rows.length?'<p>No players yet.</p>':rows.map((r,i)=>`<div class="leaderRow"><b>${i+1}</b><span>${esc(r.p.name)}</span><span>Thru ${r.thru}</span><b>${r.val===0?'E':r.val>0?'+'+r.val:r.val}</b></div>`).join(''))}
function renderScores(){if(!S.t)return;const allowed=S.role==='group'?[S.group]:[1,2,3,4,5,6];if(!allowed.includes(Number(S.group)))S.group=allowed[0];$('groupSelect').innerHTML=allowed.map(g=>`<option value="${g}" ${Number(g)===Number(S.group)?'selected':''}>Group ${g}</option>`).join('');$('groupSelect').disabled=S.role==='group'||S.role==='spectator';$('holeSelect').innerHTML=Array.from({length:S.t.holes},(_,i)=>`<option value="${i+1}" ${i+1===S.hole?'selected':''}>Hole ${i+1}</option>`).join('');const g=Number(S.group),h=Number(S.hole);const par=S.t.pars?.[h-1]||4,si=S.t.stroke_indexes?.[h-1]||h;const meta=$('scoreHoleMeta'); if(meta) meta.innerHTML=`<b>Hole ${h}</b> • Par ${par} • Handicap ${si}`;const ps=S.players.filter(p=>p.group_number===g);if(S.role==='spectator'){$('scoreGrid').innerHTML='<p>Spectator mode is view-only. Use the Leaderboard or Skins tabs.</p>';return}$('scoreGrid').innerHTML=ps.length?ps.map(p=>{const old=S.scores.find(s=>s.player_id===p.id&&s.hole===h);const netText=old?`Gross ${old.gross} • Net ${net(p,h,old.gross)}`:'Tap score';return`<div class="scoreplayer"><div class="scorePlayerHead"><b>${esc(p.name)}</b><span>HCP ${p.course_handicap||0} • ${netText}</span></div><div class="numbers">${Array.from({length:12},(_,i)=>`<button type="button" data-p="${p.id}" data-g="${g}" data-v="${i+1}" class="${old?.gross===i+1?'selected':''}">${i+1}</button>`).join('')}</div></div>`}).join(''):'<p>No players are assigned to this group yet. Add players in the Players tab.</p>';document.querySelectorAll('.numbers button').forEach(b=>b.onclick=()=>saveScore(b.dataset.p,Number(b.dataset.g),h,Number(b.dataset.v)))}
$('groupSelect').onchange=()=>{S.group=Number($('groupSelect').value);renderScores()};$('holeSelect').onchange=()=>{S.hole=Number($('holeSelect').value);renderScores()};$('prevHole').onclick=()=>{S.hole=Math.max(1,S.hole-1);renderScores()};$('nextHole').onclick=()=>{S.hole=Math.min(S.t.holes,S.hole+1);renderScores()};
async function saveScore(pid,g,h,v){try{const u=(await sb.auth.getUser()).data.user;if(!u)throw Error('Session expired. Reopen your scoring link.');const r=await sb.from('scores').upsert({tournament_id:S.tid,player_id:pid,group_number:g,hole:h,gross:v,updated_by:u.id},{onConflict:'player_id,hole'}).select();check(r);await reloadScores();toast(`${S.players.find(x=>x.id===pid)?.name}: ${v}`)}catch(e){status(e.message,true);toast(e.message)}}
function renderPlayers(){$('playerList').innerHTML=S.players.length?S.players.map(p=>`<div class="player"><b>${esc(p.name)}</b><span>HCP ${p.course_handicap||0}</span><span>Group ${p.group_number}</span></div>`).join(''):'<p>No players added yet.</p>'}
$('addPlayer').onclick=async()=>{try{const name=$('playerName').value.trim();if(!name)throw Error('Enter a player name.');const payload={tournament_id:S.tid,name,course_handicap:Number($('playerHcp').value||0),group_number:Number($('playerGroup').value)};const r=await sb.from('players').insert(payload).select().single();check(r);$('playerName').value='';await reloadPlayers();S.group=r.data.group_number;renderScores();toast(`${r.data.name} added to Group ${r.data.group_number}`)}catch(e){status(e.message,true);toast(e.message)}};
function renderSetup(){if(!admin()||!S.t)return;$('editName').value=S.t.name||'';$('editCourse').value=S.t.course||'';$('editDate').value=S.t.date||'';$('activeEvent').checked=!!S.t.is_active;$('holeSetup').innerHTML=`<div class="holeSetupHeader"><b>Hole</b><b>Par</b><b>Handicap</b><b>HCP Skin</b><b>Blind Skin</b></div>`+Array.from({length:S.t.holes},(_,i)=>{const h=i+1;return`<div class="holeRow"><b>${h}</b><input class="holePar" data-hole="${h}" type="number" min="3" max="6" value="${S.t.pars?.[i]||4}"><input class="holeSI" data-hole="${h}" type="number" min="1" max="${S.t.holes}" value="${S.t.stroke_indexes?.[i]||h}"><label class="checkLabel"><input type="checkbox" class="hcpSkin" value="${h}" ${S.t.handicap_skin_holes?.includes(h)?'checked':''}></label><label class="checkLabel"><input type="checkbox" class="blindSkin" value="${h}" ${S.t.blind_skin_holes?.includes(h)?'checked':''}></label></div>`}).join('')}
$('saveSetup').onclick=async()=>{try{const active=$('activeEvent').checked,pars=[...document.querySelectorAll('.holePar')].map(x=>Number(x.value)),stroke=[...document.querySelectorAll('.holeSI')].map(x=>Number(x.value));if(pars.some(x=>x<3||x>6))throw Error('Pars must be between 3 and 6.');if(stroke.some(x=>x<1||x>S.t.holes)||new Set(stroke).size!==S.t.holes)throw Error(`Hole handicaps must use each number 1–${S.t.holes} exactly once.`);if(active){const q=await sb.from('tournaments').update({is_active:false}).neq('id',S.tid);check(q)}const r=await sb.from('tournaments').update({name:$('editName').value,course:$('editCourse').value,date:$('editDate').value,is_active:active,pars,stroke_indexes:stroke,handicap_skin_holes:[...document.querySelectorAll('.hcpSkin:checked')].map(x=>Number(x.value)),blind_skin_holes:[...document.querySelectorAll('.blindSkin:checked')].map(x=>Number(x.value))}).eq('id',S.tid).select().single();check(r);S.t=r.data;renderAll();toast('Tournament setup saved')}catch(e){status(e.message,true);toast(e.message)}};
$('generateLinks').onclick=async()=>{try{const links={};for(let g=1;g<=6;g++){const tok=randomToken();links[g]=tok;check(await sb.from('group_links').upsert({tournament_id:S.tid,group_number:g,token:tok},{onConflict:'tournament_id,group_number'}))}renderLinks(links)}catch(e){status(e.message,true);toast(e.message)}};
function renderLinks(tokens){if(!tokens){$('links').innerHTML='<p>Generate links to display a new set.</p>';return}const base=location.origin+location.pathname;$('links').innerHTML=Object.entries(tokens).map(([g,t])=>{const u=`${base}?t=${S.tid}&g=${g}&token=${t}`;return`<div class="linkrow"><b>Group ${g}</b><br><input readonly value="${u}"><button data-copy="${u}">Copy</button></div>`}).join('')+`<div class="linkrow"><b>Spectator</b><br><input readonly value="${base}?spectator=1"><button data-copy="${base}?spectator=1">Copy</button></div>`;document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy);toast('Copied')})}
$('clearScores').onclick=async()=>{if(!confirm('Clear every score while keeping the tournament, course and players?'))return;try{const r=await sb.from('scores').delete().eq('tournament_id',S.tid);check(r);await reloadScores();toast('Scores cleared')}catch(e){status(e.message,true);toast(e.message)}};
function skinResults(holes,isNet){return holes?.map(h=>{const es=S.players.map(p=>{const s=S.scores.find(x=>x.player_id===p.id&&x.hole===h);return s?{p,v:isNet?net(p,h,s.gross):s.gross}:null}).filter(Boolean);if(es.length<S.players.length)return`<div class="skinrow">Hole ${h}: waiting (${es.length}/${S.players.length})</div>`;const low=Math.min(...es.map(x=>x.v)),wins=es.filter(x=>x.v===low);return`<div class="skinrow"><b>Hole ${h}</b>: ${wins.map(x=>esc(x.p.name)).join(', ')} (${low})</div>`}).join('')||'<p>No holes selected.</p>'}
function renderSkins(){if(!S.t)return;$('handicapSkins').innerHTML=skinResults(S.t.handicap_skin_holes,true);$('blindSkins').innerHTML=skinResults(S.t.blind_skin_holes,false);if(admin())renderLinks()}
window.addEventListener('error',e=>status(e.message,true));boot();
})();
